### ISSUE TITLE
Please add our CVPR 2022 paper.

### ISSUE THREAD

**Issue by revisitq** [extreme-assistant/CVPR2022-Paper-Code-Interpretation#63]
Please add our CVPR 2022 paper in 3D Object Detection: Pseudo-Stereo for Monocular 3D Object Detection in Autonomous Driving

paper link: https://arxiv.org/abs/2203.02112
code link: https://github.com/revisitq/Pseudo-Stereo-3D

Thanks very much!

**Comment by extreme-assistant** [comment]
It has been added, thanks for your information~
