### ISSUE TITLE
Please add our CVPR 2022 paper

### ISSUE THREAD

**Issue by Vegetebird** [extreme-assistant/CVPR2022-Paper-Code-Interpretation#65]
Please add our CVPR 2022 paper in 3D Human Pose Estimation/Pose Estimation/Transformer/3D Vision/3D Human Reconstruction: 
MHFormer: Multi-Hypothesis Transformer for 3D Human Pose Estimation

paper link: https://arxiv.org/pdf/2111.12707.pdf
code link: https://github.com/Vegetebird/MHFormer

Thanks very much!

**Comment by extreme-assistant** [comment]
It has been added, thanks for your information~
