### ISSUE TITLE
Please add our CVPR 2022 paper for 3D human pose estimation

### ISSUE THREAD

**Issue by YxZhxn** [extreme-assistant/CVPR2022-Paper-Code-Interpretation#70]
Hello, please add our CVPR 2022 paper. Thanks in advance!

Category:  3D human pose estimation
Title: Ray3D: ray-based 3D human pose estimation for monocular absolute 3D localization
Arxiv: https://arxiv.org/abs/2203.11471
Repository: https://github.com/YxZhxn/Ray3D

**Comment by extreme-assistant** [comment]
It has been added, thanks for your information~
