### ISSUE TITLE
Please update a paper

### ISSUE THREAD

**Issue by tmp12316** [extreme-assistant/CVPR2022-Paper-Code-Interpretation#76]
Please update an oral paper. Thanks!

Arxiv: https://arxiv.org/abs/2203.06398
Code: https://github.com/CityU-AIM-Group/SIGMA
Zhihu: https://zhuanlan.zhihu.com/p/492956292

**Comment by awa121** [comment]
Thank you for your email. I apologize that I am unable to respond to you immediately, but will do so as soon as I am back in the office.Have a nice day! LIU.Y.
